## Deliverable 2. Create a Customer Travel Destinations Map.

In [44]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [45]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Qaanaaq,GL,77.48,-69.36,28.92,85,0,6.85,clear sky
1,1,Rikitea,PF,-23.12,-134.97,73.44,78,46,18.72,scattered clouds
2,2,Lorengau,PG,-2.02,147.27,81.46,71,42,3.36,scattered clouds
3,3,Ushuaia,AR,-54.80,-68.30,53.60,50,40,6.93,scattered clouds
4,4,Khatanga,RU,71.97,102.50,16.84,97,100,3.74,light snow

In [46]:
city_data_df.dtypes

City ID                  int64
City                    object
Country                 object
Lat                    float64
Lng                    float64
Max Temp               float64
Humidity                 int64
Cloudiness               int64
Wind Speed             float64
Current Description     object
dtype: object

In [47]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_weather = float(input("What is the coolest temperature you preferred on your trip?"))
max_weather = float(input("What is the warmest temperature you preferred on your trip?"))

What is the coolest temperature you preferred on your trip?70
What is the warmest temperature you preferred on your trip?90

In [48]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
ideal_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_weather) & \
                                   (city_data_df["Max Temp"] >= min_weather)]

ideal_cities_df.head(10)

,City ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Rikitea,PF,-23.12,-134.97,73.44,78,46,18.72,scattered clouds
2,2,Lorengau,PG,-2.02,147.27,81.46,71,42,3.36,scattered clouds
6,6,Hambantota,LK,6.12,81.12,82.40,83,75,5.82,light rain
10,10,Castro,BR,-24.79,-50.01,71.11,74,98,7.11,overcast clouds
12,12,Perdoes,BR,-21.09,-45.09,83.34,46,94,5.99,overcast clouds
15,15,Arraial Do Cabo,BR,-22.97,-42.03,77.00,83,90,18.34,overcast clouds
16,16,Ribeira Grande,PT,38.52,-28.70,75.20,69,40,5.82,scattered clouds
17,17,Vaini,TO,-21.20,-175.20,73.40,83,75,6.93,broken clouds
18,18,Fethiye,TR,36.62,29.12,80.60,51,20,16.11,few clouds
19,19,Cabo San Lucas,MX,22.89,-109.91,75.99,78,5,11.99,clear sky

In [49]:
# 4a. Determine if there are any empty rows.
ideal_cities_df.count()

City ID                840
City                   840
Country                839
Lat                    840
Lng                    840
Max Temp               840
Humidity               840
Cloudiness             840
Wind Speed             840
Current Description    840
dtype: int64

In [50]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
ideal_cities_new_df = ideal_cities_df.dropna()
ideal_cities_new_df.head(10)

,City ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Rikitea,PF,-23.12,-134.97,73.44,78,46,18.72,scattered clouds
2,2,Lorengau,PG,-2.02,147.27,81.46,71,42,3.36,scattered clouds
6,6,Hambantota,LK,6.12,81.12,82.40,83,75,5.82,light rain
10,10,Castro,BR,-24.79,-50.01,71.11,74,98,7.11,overcast clouds
12,12,Perdoes,BR,-21.09,-45.09,83.34,46,94,5.99,overcast clouds
15,15,Arraial Do Cabo,BR,-22.97,-42.03,77.00,83,90,18.34,overcast clouds
16,16,Ribeira Grande,PT,38.52,-28.70,75.20,69,40,5.82,scattered clouds
17,17,Vaini,TO,-21.20,-175.20,73.40,83,75,6.93,broken clouds
18,18,Fethiye,TR,36.62,29.12,80.60,51,20,16.11,few clouds
19,19,Cabo San Lucas,MX,22.89,-109.91,75.99,78,5,11.99,clear sky

In [51]:
ideal_cities_new_df.count()

City ID                839
City                   839
Country                839
Lat                    839
Lng                    839
Max Temp               839
Humidity               839
Cloudiness             839
Wind Speed             839
Current Description    839
dtype: int64

In [52]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = ideal_cities_new_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Rikitea,PF,73.44,scattered clouds,-23.12,-134.97,
2,Lorengau,PG,81.46,scattered clouds,-2.02,147.27,
6,Hambantota,LK,82.40,light rain,6.12,81.12,
10,Castro,BR,71.11,overcast clouds,-24.79,-50.01,
12,Perdoes,BR,83.34,overcast clouds,-21.09,-45.09,
15,Arraial Do Cabo,BR,77.00,overcast clouds,-22.97,-42.03,
16,Ribeira Grande,PT,75.20,scattered clouds,38.52,-28.70,
17,Vaini,TO,73.40,broken clouds,-21.20,-175.20,
18,Fethiye,TR,80.60,few clouds,36.62,29.12,
19,Cabo San Lucas,MX,75.99,clear sky,22.89,-109.91,

In [53]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():

    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"

    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except(IndexError):                                                   
        print("Hotel not found...skipping")

Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping

In [54]:
hotel_df.count()

City                   839
Country                839
Max Temp               839
Current Description    839
Lat                    839
Lng                    839
Hotel Name             839
dtype: int64

In [55]:
 hotel_df.dtypes

City                    object
Country                 object
Max Temp               float64
Current Description     object
Lat                    float64
Lng                    float64
Hotel Name              object
dtype: object

In [56]:
empty = (hotel_df['Hotel Name'] == '').sum()
print(empty)

72

In [57]:
hotel_df.tail(20)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2018,Itacare,BR,80.89,clear sky,-14.28,-39.00,Ecoporan Hotel Charme Spa & Eventos
2022,Pringsewu,ID,75.45,light rain,-5.36,104.97,Urban Style by Front One
2024,Riberalta,BO,82.40,smoke,-10.98,-66.10,Hotel Colonial
2026,Calbayog,PH,77.34,overcast clouds,12.07,124.60,Ciriaco Hotel & Resort
2028,Chirongui,YT,82.40,overcast clouds,-12.93,45.15,La Villa Mahatsara
2029,Quarai,BR,71.15,broken clouds,-30.39,-56.45,Hotel Casino San Eugenio del Cuareim
2036,Ziro,IN,84.20,mist,27.63,93.83,Ka-ngam homestay
2037,Brownsville,US,81.00,broken clouds,25.90,-97.50,Hotel Alameda Express
2048,Ventersburg,ZA,89.89,clear sky,-28.09,27.14,Palms Guesthouse
2051,Keroka,KE,74.26,few clouds,-0.78,34.95,Bunker Hotel Keroka
2052,Ransang,PH,78.40,overcast clouds,8.96,117.58,
2056,Spring Hill,US,80.01,clear sky,28.48,-82.53,Room of The world By traveline Plus
2057,Raga,SS,86.43,scattered clouds,8.46,25.68,
2059,Letlhakane,BW,89.08,few clouds,-21.42,25.58,Motswedi Hotel P650
2060,Anloga,GH,86.00,few clouds,5.79,0.90,Pin Drop Hotel
2061,Mocorito,MX,80.01,clear sky,25.48,-107.92,Casa de Don Eustaquio
2062,Dahra,DZ,75.20,scattered clouds,36.25,0.85,Ein Mtabol
2063,Mandali,IQ,87.53,clear sky,33.75,45.55,بيت خالد امين
2064,Coari,BR,88.88,overcast clouds,-4.08,-63.14,HOTEL ALEX FLAT
2067,La Asuncion,VE,83.37,clear sky,11.03,-63.86,Colinas de Matasiete

In [58]:
# Replace empty hotel names with NaN
hotel_df.loc[(hotel_df)["Hotel Name"] ==''] = np.nan
hotel_df.tail(20)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2018,Itacare,BR,80.89,clear sky,-14.28,-39.00,Ecoporan Hotel Charme Spa & Eventos
2022,Pringsewu,ID,75.45,light rain,-5.36,104.97,Urban Style by Front One
2024,Riberalta,BO,82.40,smoke,-10.98,-66.10,Hotel Colonial
2026,Calbayog,PH,77.34,overcast clouds,12.07,124.60,Ciriaco Hotel & Resort
2028,Chirongui,YT,82.40,overcast clouds,-12.93,45.15,La Villa Mahatsara
2029,Quarai,BR,71.15,broken clouds,-30.39,-56.45,Hotel Casino San Eugenio del Cuareim
2036,Ziro,IN,84.20,mist,27.63,93.83,Ka-ngam homestay
2037,Brownsville,US,81.00,broken clouds,25.90,-97.50,Hotel Alameda Express
2048,Ventersburg,ZA,89.89,clear sky,-28.09,27.14,Palms Guesthouse
2051,Keroka,KE,74.26,few clouds,-0.78,34.95,Bunker Hotel Keroka
2052,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2056,Spring Hill,US,80.01,clear sky,28.48,-82.53,Room of The world By traveline Plus
2057,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2059,Letlhakane,BW,89.08,few clouds,-21.42,25.58,Motswedi Hotel P650
2060,Anloga,GH,86.00,few clouds,5.79,0.90,Pin Drop Hotel
2061,Mocorito,MX,80.01,clear sky,25.48,-107.92,Casa de Don Eustaquio
2062,Dahra,DZ,75.20,scattered clouds,36.25,0.85,Ein Mtabol
2063,Mandali,IQ,87.53,clear sky,33.75,45.55,بيت خالد امين
2064,Coari,BR,88.88,overcast clouds,-4.08,-63.14,HOTEL ALEX FLAT
2067,La Asuncion,VE,83.37,clear sky,11.03,-63.86,Colinas de Matasiete

In [59]:
# 7. Drop the rows where there is no Hotel Name.
hotel_clean_df = hotel_df.dropna()

hotel_clean_df.tail(20)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2015,Alleroy,RU,71.60,scattered clouds,43.21,46.28,Kacheli-Siti
2016,Yabrud,SY,86.00,clear sky,33.97,36.66,صالون مها حيدر - Salon Maha
2018,Itacare,BR,80.89,clear sky,-14.28,-39.00,Ecoporan Hotel Charme Spa & Eventos
2022,Pringsewu,ID,75.45,light rain,-5.36,104.97,Urban Style by Front One
2024,Riberalta,BO,82.40,smoke,-10.98,-66.10,Hotel Colonial
2026,Calbayog,PH,77.34,overcast clouds,12.07,124.60,Ciriaco Hotel & Resort
2028,Chirongui,YT,82.40,overcast clouds,-12.93,45.15,La Villa Mahatsara
2029,Quarai,BR,71.15,broken clouds,-30.39,-56.45,Hotel Casino San Eugenio del Cuareim
2036,Ziro,IN,84.20,mist,27.63,93.83,Ka-ngam homestay
2037,Brownsville,US,81.00,broken clouds,25.90,-97.50,Hotel Alameda Express
2048,Ventersburg,ZA,89.89,clear sky,-28.09,27.14,Palms Guesthouse
2051,Keroka,KE,74.26,few clouds,-0.78,34.95,Bunker Hotel Keroka
2056,Spring Hill,US,80.01,clear sky,28.48,-82.53,Room of The world By traveline Plus
2059,Letlhakane,BW,89.08,few clouds,-21.42,25.58,Motswedi Hotel P650
2060,Anloga,GH,86.00,few clouds,5.79,0.90,Pin Drop Hotel
2061,Mocorito,MX,80.01,clear sky,25.48,-107.92,Casa de Don Eustaquio
2062,Dahra,DZ,75.20,scattered clouds,36.25,0.85,Ein Mtabol
2063,Mandali,IQ,87.53,clear sky,33.75,45.55,بيت خالد امين
2064,Coari,BR,88.88,overcast clouds,-4.08,-63.14,HOTEL ALEX FLAT
2067,La Asuncion,VE,83.37,clear sky,11.03,-63.86,Colinas de Matasiete

In [60]:
hotel_clean_df.count()

City                   767
Country                767
Max Temp               767
Current Description    767
Lat                    767
Lng                    767
Hotel Name             767
dtype: int64

In [61]:
# 8a. Create the output File (CSV)
output_data_file ="WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
hotel_clean_df.to_csv(output_data_file, index_label="City_ID")

In [62]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>

</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_clean_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_clean_df[["Lat", "Lng"]]

In [63]:
# 11a. Add a marker layer for each city to the map. 
locations = hotel_clean_df[["Lat","Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))